### ISSUE TITLE
Event Manager: Receiving error relating to CSV header conversion?

### ISSUE THREAD

**Issue by itiswicked** [JumpstartLab/curriculum#1048]
Hello, I am working through this tutorial and find myself stuck when trying to access columns by their name symbols. My assumption is that the issue is that CSV is having trouble converting the headers so therefore I cannot access the columns by using `:first_name`, `:zipcode`, etc.

/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/csv.rb:2172:in `block (2 levels) in convert_fields': undefined method `arity' for nil:NilClass (NoMethodError)
from /.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/csv.rb:2171:in `each'
from /.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/csv.rb:2171:in `block in convert_fields'
from /.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/csv.rb:2170:in `map'
from /.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/csv.rb:2170:in `with_index'
from /.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/csv.rb:2170:in `convert_fields'
from /.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/csv.rb:2211:in `parse_headers'
from /.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/csv.rb:1885:in `block in shift'
from /.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/csv.rb:1777:in `loop'
from /.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/csv.rb:1777:in `shift'
from /.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/csv.rb:1719:in `each'
from lib/event_manager.rb:5:in `<main>'

Cut down the file paths for a little bit of brevity. I apoligize that each error ins't on its own line. I'm not sure why that is. Since I'm not familiar with the CSV library, any help is appreciated, thanks!

**Comment by itiswicked** [comment]
My apologies, I just now found a solution to this issue [here](https://github.com/JumpstartLab/curriculum/issues/537).
